/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

export const controllers = {
  Articles: () => import('#controllers/articles_controller'),
  auth: {
    Github: () => import('#controllers/auth/github_controller'),
    Login: () => import('#controllers/auth/login_controller'),
    Register: () => import('#controllers/auth/register_controller'),
  },
  Home: () => import('#controllers/home_controller'),
  Markdown: () => import('#controllers/markdown_controller'),
  Profile: () => import('#controllers/profile_controller'),
  Replies: () => import('#controllers/replies_controller'),
  Seo: () => import('#controllers/seo_controller'),
}
