/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'

export class ArticleTagSchema extends BaseModel {
  static $columns = ['articleId', 'tagId'] as const
  $columns = ArticleTagSchema.$columns
  @column({ isPrimary: true })
  declare articleId: number
  @column()
  declare tagId: number
}

export class ArticleSchema extends BaseModel {
  static $columns = ['body', 'bodyHtml', 'coverUrl', 'createdAt', 'excerpt', 'featuredAt', 'id', 'publishedAt', 'readingMinutes', 'slug', 'title', 'updatedAt', 'userId', 'viewsCount'] as const
  $columns = ArticleSchema.$columns
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column()
  declare coverUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string | null
  @column.dateTime()
  declare featuredAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare readingMinutes: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewsCount: number
}

export class ChannelSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'position', 'slug', 'updatedAt'] as const
  $columns = ChannelSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DiscussionTagSchema extends BaseModel {
  static $columns = ['discussionId', 'tagId'] as const
  $columns = DiscussionTagSchema.$columns
  @column({ isPrimary: true })
  declare discussionId: number
  @column()
  declare tagId: number
}

export class DiscussionSchema extends BaseModel {
  static $columns = ['body', 'bodyHtml', 'createdAt', 'id', 'lastActivityAt', 'lockedAt', 'pinnedAt', 'repliesCount', 'slug', 'title', 'updatedAt', 'userId', 'viewsCount'] as const
  $columns = DiscussionSchema.$columns
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column.dateTime()
  declare pinnedAt: DateTime | null
  @column()
  declare repliesCount: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewsCount: number
}

export class LikeSchema extends BaseModel {
  static $columns = ['articleId', 'createdAt', 'id', 'replyId', 'userId'] as const
  $columns = LikeSchema.$columns
  @column()
  declare articleId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare replyId: number | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReplySchema extends BaseModel {
  static $columns = ['articleId', 'body', 'bodyHtml', 'createdAt', 'discussionId', 'id', 'threadId', 'updatedAt', 'userId'] as const
  $columns = ReplySchema.$columns
  @column()
  declare articleId: number | null
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discussionId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare threadId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class TagSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ThreadSchema extends BaseModel {
  static $columns = ['body', 'bodyHtml', 'channelId', 'createdAt', 'id', 'lastActivityAt', 'lockedAt', 'pinnedAt', 'repliesCount', 'slug', 'solutionReplyId', 'title', 'updatedAt', 'userId', 'viewsCount'] as const
  $columns = ThreadSchema.$columns
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column()
  declare channelId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column.dateTime()
  declare pinnedAt: DateTime | null
  @column()
  declare repliesCount: number
  @column()
  declare slug: string
  @column()
  declare solutionReplyId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewsCount: number
}

export class UserSchema extends BaseModel {
  static $columns = ['avatarUrl', 'bannedAt', 'bio', 'createdAt', 'email', 'emailVerifiedAt', 'githubId', 'githubUsername', 'id', 'linkedinUsername', 'location', 'name', 'password', 'role', 'twitterUsername', 'updatedAt', 'username', 'websiteUrl'] as const
  $columns = UserSchema.$columns
  @column()
  declare avatarUrl: string | null
  @column.dateTime()
  declare bannedAt: DateTime | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare githubId: string | null
  @column()
  declare githubUsername: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare linkedinUsername: string | null
  @column()
  declare location: string | null
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare role: 'member' | 'moderator' | 'admin'
  @column()
  declare twitterUsername: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare websiteUrl: string | null
}
