/**
 * This file is automatically generated
 * DO NOT EDIT manually
 * Run "node ace migration:run" command to re-generate this file
 */

import { BaseModel, column } from '@adonisjs/lucid/orm'
import { DateTime } from 'luxon'
import { jsonArrayColumn } from '#database/json_column'
import type { ProfileLink } from '#database/json_column'

export class ArticleTagSchema extends BaseModel {
  static $columns = ['articleId', 'tagId'] as const
  $columns = ArticleTagSchema.$columns
  @column({ isPrimary: true })
  declare articleId: number
  @column()
  declare tagId: number
}

export class ArticleSchema extends BaseModel {
  static $columns = ['body', 'bodyHtml', 'coverUrl', 'createdAt', 'excerpt', 'featuredAt', 'id', 'publishedAt', 'readingMinutes', 'slug', 'title', 'updatedAt', 'userId', 'viewsCount'] as const
  $columns = ArticleSchema.$columns
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column()
  declare coverUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare excerpt: string | null
  @column.dateTime()
  declare featuredAt: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare readingMinutes: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewsCount: number
}

export class ChannelSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'id', 'name', 'position', 'slug', 'updatedAt'] as const
  $columns = ChannelSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class DiscussionTagSchema extends BaseModel {
  static $columns = ['discussionId', 'tagId'] as const
  $columns = DiscussionTagSchema.$columns
  @column({ isPrimary: true })
  declare discussionId: number
  @column()
  declare tagId: number
}

export class DiscussionSchema extends BaseModel {
  static $columns = ['body', 'bodyHtml', 'createdAt', 'id', 'lastActivityAt', 'lockedAt', 'pinnedAt', 'repliesCount', 'slug', 'title', 'updatedAt', 'userId', 'viewsCount'] as const
  $columns = DiscussionSchema.$columns
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column.dateTime()
  declare pinnedAt: DateTime | null
  @column()
  declare repliesCount: number
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewsCount: number
}

export class EventRegistrationSchema extends BaseModel {
  static $columns = ['checkedInAt', 'createdAt', 'eventId', 'id', 'remindedAt', 'status', 'ticketCode', 'updatedAt', 'userId'] as const
  $columns = EventRegistrationSchema.$columns
  @column.dateTime()
  declare checkedInAt: DateTime | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare eventId: number
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare remindedAt: DateTime | null
  @column()
  declare status: 'going' | 'waitlist' | 'cancelled'
  @column()
  declare ticketCode: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class EventSchema extends BaseModel {
  static $columns = ['address', 'capacity', 'city', 'coverUrl', 'createdAt', 'description', 'descriptionHtml', 'endsAt', 'format', 'id', 'mapUrl', 'onlineUrl', 'slug', 'startsAt', 'status', 'summary', 'title', 'updatedAt', 'userId', 'venueName'] as const
  $columns = EventSchema.$columns
  @column()
  declare address: string | null
  @column()
  declare capacity: number | null
  @column()
  declare city: string | null
  @column()
  declare coverUrl: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare descriptionHtml: string
  @column.dateTime()
  declare endsAt: DateTime | null
  @column()
  declare format: 'in_person' | 'online' | 'hybrid'
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare mapUrl: string | null
  @column()
  declare onlineUrl: string | null
  @column()
  declare slug: string
  @column.dateTime()
  declare startsAt: DateTime
  @column()
  declare status: 'draft' | 'published' | 'cancelled'
  @column()
  declare summary: string | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number | null
  @column()
  declare venueName: string | null
}

export class JobSchema extends BaseModel {
  static $columns = ['applyClicks', 'applyEmail', 'applyUrl', 'companyLogoUrl', 'companyName', 'companyUrl', 'contract', 'createdAt', 'description', 'descriptionHtml', 'expiresAt', 'featuredUntil', 'id', 'location', 'publishedAt', 'rejectionReason', 'remote', 'salaryCurrency', 'salaryMax', 'salaryMin', 'salaryPeriod', 'skills', 'slug', 'status', 'title', 'updatedAt', 'userId', 'viewsCount'] as const
  $columns = JobSchema.$columns
  @column()
  declare applyClicks: number
  @column()
  declare applyEmail: string | null
  @column()
  declare applyUrl: string | null
  @column()
  declare companyLogoUrl: string | null
  @column()
  declare companyName: string
  @column()
  declare companyUrl: string | null
  @column()
  declare contract: 'cdi' | 'cdd' | 'freelance' | 'stage' | 'alternance'
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string
  @column()
  declare descriptionHtml: string
  @column.dateTime()
  declare expiresAt: DateTime | null
  @column.dateTime()
  declare featuredUntil: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare location: string | null
  @column.dateTime()
  declare publishedAt: DateTime | null
  @column()
  declare rejectionReason: string | null
  @column()
  declare remote: 'onsite' | 'hybrid' | 'remote'
  @column()
  declare salaryCurrency: string
  @column()
  declare salaryMax: number | null
  @column()
  declare salaryMin: number | null
  @column()
  declare salaryPeriod: 'month' | 'year' | 'day' | 'project'
  @jsonArrayColumn()
  declare skills: string[]
  @column()
  declare slug: string
  @column()
  declare status: 'pending' | 'published' | 'rejected' | 'expired' | 'closed'
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewsCount: number
}

export class LearningPathSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'descriptionHtml', 'id', 'isPublished', 'level', 'position', 'slug', 'summary', 'title', 'updatedAt'] as const
  $columns = LearningPathSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column()
  declare descriptionHtml: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isPublished: boolean
  @column()
  declare level: 'debutant' | 'intermediaire' | 'avance'
  @column()
  declare position: number
  @column()
  declare slug: string
  @column()
  declare summary: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LearningProgressSchema extends BaseModel {
  static $columns = ['completedAt', 'stepId', 'userId'] as const
  $columns = LearningProgressSchema.$columns
  @column.dateTime()
  declare completedAt: DateTime
  @column()
  declare stepId: number
  @column({ isPrimary: true })
  declare userId: number
}

export class LearningStepSchema extends BaseModel {
  static $columns = ['articleId', 'body', 'bodyHtml', 'createdAt', 'estimatedMinutes', 'id', 'pathId', 'position', 'resourceUrl', 'slug', 'title', 'updatedAt'] as const
  $columns = LearningStepSchema.$columns
  @column()
  declare articleId: number | null
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare estimatedMinutes: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare pathId: number
  @column()
  declare position: number
  @column()
  declare resourceUrl: string | null
  @column()
  declare slug: string
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class LikeSchema extends BaseModel {
  static $columns = ['articleId', 'createdAt', 'id', 'replyId', 'userId'] as const
  $columns = LikeSchema.$columns
  @column()
  declare articleId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare replyId: number | null
  @column()
  declare userId: number
}

export class MediaSchema extends BaseModel {
  static $columns = ['alt', 'createdAt', 'height', 'id', 'key', 'mime', 'size', 'userId', 'width'] as const
  $columns = MediaSchema.$columns
  @column()
  declare alt: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare height: number
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare key: string
  @column()
  declare mime: string
  @column()
  declare size: number
  @column()
  declare userId: number | null
  @column()
  declare width: number
}

export class NotificationSchema extends BaseModel {
  static $columns = ['actorId', 'articleId', 'createdAt', 'discussionId', 'id', 'readAt', 'replyId', 'threadId', 'title', 'type', 'url', 'userId'] as const
  $columns = NotificationSchema.$columns
  @column()
  declare actorId: number | null
  @column()
  declare articleId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discussionId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare readAt: DateTime | null
  @column()
  declare replyId: number | null
  @column()
  declare threadId: number | null
  @column()
  declare title: string | null
  @column()
  declare type: 'thread_reply' | 'discussion_reply' | 'article_comment' | 'solution_accepted' | 'job_approved' | 'job_rejected' | 'event_reminder' | 'event_promoted' | 'event_cancelled'
  @column()
  declare url: string | null
  @column()
  declare userId: number
}

export class RateLimitSchema extends BaseModel {
  static $columns = ['expire', 'key', 'points'] as const
  $columns = RateLimitSchema.$columns
  @column()
  declare expire: bigint | number | null
  @column({ isPrimary: true })
  declare key: string
  @column()
  declare points: number
}

export class RememberMeTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'expiresAt', 'hash', 'id', 'tokenableId', 'updatedAt'] as const
  $columns = RememberMeTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column.dateTime()
  declare expiresAt: DateTime
  @column()
  declare hash: string
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare tokenableId: number
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime
}

export class ReplySchema extends BaseModel {
  static $columns = ['articleId', 'body', 'bodyHtml', 'createdAt', 'discussionId', 'id', 'threadId', 'updatedAt', 'userId'] as const
  $columns = ReplySchema.$columns
  @column()
  declare articleId: number | null
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare discussionId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare threadId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
}

export class ReportSchema extends BaseModel {
  static $columns = ['articleId', 'createdAt', 'details', 'discussionId', 'id', 'reason', 'replyId', 'reporterId', 'resolvedAt', 'resolvedById', 'status', 'targetId', 'targetLabel', 'targetOwnerId', 'targetType', 'threadId', 'updatedAt'] as const
  $columns = ReportSchema.$columns
  @column()
  declare articleId: number | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare details: string | null
  @column()
  declare discussionId: number | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare reason: 'spam' | 'abuse' | 'off_topic' | 'other'
  @column()
  declare replyId: number | null
  @column()
  declare reporterId: number
  @column.dateTime()
  declare resolvedAt: DateTime | null
  @column()
  declare resolvedById: number | null
  @column()
  declare status: 'open' | 'resolved' | 'dismissed'
  @column()
  declare targetId: number
  @column()
  declare targetLabel: string | null
  @column()
  declare targetOwnerId: number | null
  @column()
  declare targetType: 'article' | 'thread' | 'discussion' | 'reply'
  @column()
  declare threadId: number | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class SponsorSchema extends BaseModel {
  static $columns = ['createdAt', 'description', 'endsOn', 'id', 'isActive', 'logoUrl', 'name', 'position', 'slug', 'startsOn', 'tier', 'updatedAt', 'websiteUrl'] as const
  $columns = SponsorSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column.date()
  declare endsOn: DateTime | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare isActive: boolean
  @column()
  declare logoUrl: string | null
  @column()
  declare name: string
  @column()
  declare position: number
  @column()
  declare slug: string
  @column.date()
  declare startsOn: DateTime | null
  @column()
  declare tier: 'platinum' | 'gold' | 'silver' | 'community'
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare websiteUrl: string | null
}

export class TagSchema extends BaseModel {
  static $columns = ['body', 'bodyHtml', 'createdAt', 'description', 'id', 'name', 'slug', 'updatedAt'] as const
  $columns = TagSchema.$columns
  @column()
  declare body: string | null
  @column()
  declare bodyHtml: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare description: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare name: string
  @column()
  declare slug: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
}

export class ThreadSchema extends BaseModel {
  static $columns = ['body', 'bodyHtml', 'channelId', 'createdAt', 'id', 'lastActivityAt', 'lockedAt', 'pinnedAt', 'repliesCount', 'slug', 'solutionReplyId', 'title', 'updatedAt', 'userId', 'viewsCount'] as const
  $columns = ThreadSchema.$columns
  @column()
  declare body: string
  @column()
  declare bodyHtml: string
  @column()
  declare channelId: number
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column.dateTime()
  declare lastActivityAt: DateTime
  @column.dateTime()
  declare lockedAt: DateTime | null
  @column.dateTime()
  declare pinnedAt: DateTime | null
  @column()
  declare repliesCount: number
  @column()
  declare slug: string
  @column()
  declare solutionReplyId: number | null
  @column()
  declare title: string
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare userId: number
  @column()
  declare viewsCount: number
}

export class UserTokenSchema extends BaseModel {
  static $columns = ['createdAt', 'email', 'expiresAt', 'id', 'tokenHash', 'type', 'usedAt', 'userId'] as const
  $columns = UserTokenSchema.$columns
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare email: string | null
  @column.dateTime()
  declare expiresAt: DateTime
  @column({ isPrimary: true })
  declare id: number
  @column({ serializeAs: null })
  declare tokenHash: string
  @column()
  declare type: 'password_reset' | 'email_verification'
  @column.dateTime()
  declare usedAt: DateTime | null
  @column()
  declare userId: number
}

export class UserSchema extends BaseModel {
  static $columns = ['appleId', 'availability', 'avatarUrl', 'bannedAt', 'bio', 'createdAt', 'cvOriginalName', 'cvPath', 'cvSize', 'cvUploadedAt', 'cvVisibility', 'email', 'emailNotifications', 'emailVerifiedAt', 'githubId', 'githubUsername', 'googleId', 'headline', 'id', 'linkedinUsername', 'links', 'locale', 'location', 'name', 'password', 'portfolioUrl', 'role', 'sessionVersion', 'skills', 'twitterUsername', 'updatedAt', 'username', 'websiteUrl', 'weeklyDigest'] as const
  $columns = UserSchema.$columns
  @column()
  declare appleId: string | null
  @column()
  declare availability: 'open_to_work' | 'freelance' | 'hiring' | null
  @column()
  declare avatarUrl: string | null
  @column.dateTime()
  declare bannedAt: DateTime | null
  @column()
  declare bio: string | null
  @column.dateTime({ autoCreate: true })
  declare createdAt: DateTime
  @column()
  declare cvOriginalName: string | null
  @column({ serializeAs: null })
  declare cvPath: string | null
  @column()
  declare cvSize: number | null
  @column.dateTime()
  declare cvUploadedAt: DateTime | null
  @column()
  declare cvVisibility: 'public' | 'members' | 'private'
  @column()
  declare email: string
  @column()
  declare emailNotifications: boolean
  @column.dateTime()
  declare emailVerifiedAt: DateTime | null
  @column()
  declare githubId: string | null
  @column()
  declare githubUsername: string | null
  @column()
  declare googleId: string | null
  @column()
  declare headline: string | null
  @column({ isPrimary: true })
  declare id: number
  @column()
  declare linkedinUsername: string | null
  @jsonArrayColumn()
  declare links: ProfileLink[]
  @column()
  declare locale: 'fr' | 'en' | null
  @column()
  declare location: string | null
  @column()
  declare name: string | null
  @column({ serializeAs: null })
  declare password: string | null
  @column()
  declare portfolioUrl: string | null
  @column()
  declare role: 'member' | 'moderator' | 'admin'
  @column()
  declare sessionVersion: number
  @jsonArrayColumn()
  declare skills: string[]
  @column()
  declare twitterUsername: string | null
  @column.dateTime({ autoCreate: true, autoUpdate: true })
  declare updatedAt: DateTime | null
  @column()
  declare username: string
  @column()
  declare websiteUrl: string | null
  @column()
  declare weeklyDigest: boolean
}
