/**
 * This file is automatically generated.
 * DO NOT EDIT manually
 */

/// <reference path="./manifest.d.ts" />
import type { InferData, InferVariants } from '@adonisjs/core/types/transformers'
import type { InferSharedProps, InferFlashData } from '@adonisjs/inertia/types'
import type ArticleTransformer from '#transformers/article_transformer'
import type ChannelTransformer from '#transformers/channel_transformer'
import type DiscussionTransformer from '#transformers/discussion_transformer'
import type NotificationTransformer from '#transformers/notification_transformer'
import type ReplyTransformer from '#transformers/reply_transformer'
import type ReportTransformer from '#transformers/report_transformer'
import type TagTransformer from '#transformers/tag_transformer'
import type ThreadTransformer from '#transformers/thread_transformer'
import type UserTransformer from '#transformers/user_transformer'
import type InertiaMiddleware from '#middleware/inertia_middleware'

export namespace Data {
  export type Article = InferData<ArticleTransformer>
  export namespace Article {
    export type Variants = InferVariants<ArticleTransformer>
  }
  export type Channel = InferData<ChannelTransformer>
  export namespace Channel {
    export type Variants = InferVariants<ChannelTransformer>
  }
  export type Discussion = InferData<DiscussionTransformer>
  export namespace Discussion {
    export type Variants = InferVariants<DiscussionTransformer>
  }
  export type Notification = InferData<NotificationTransformer>
  export namespace Notification {
    export type Variants = InferVariants<NotificationTransformer>
  }
  export type Reply = InferData<ReplyTransformer>
  export namespace Reply {
    export type Variants = InferVariants<ReplyTransformer>
  }
  export type Report = InferData<ReportTransformer>
  export namespace Report {
    export type Variants = InferVariants<ReportTransformer>
  }
  export type Tag = InferData<TagTransformer>
  export namespace Tag {
    export type Variants = InferVariants<TagTransformer>
  }
  export type Thread = InferData<ThreadTransformer>
  export namespace Thread {
    export type Variants = InferVariants<ThreadTransformer>
  }
  export type User = InferData<UserTransformer>
  export namespace User {
    export type Variants = InferVariants<UserTransformer>
  }
  export type SharedProps = InferSharedProps<InertiaMiddleware>
  export type FlashMessages = InferFlashData<InertiaMiddleware>
}
